export const SET_COUNTER = 'SET_COUNTER';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const SET_COUNTER2 = 'SET_COUNTER2';
export const CLEAR_COUNTER2 = 'CLEAR_COUNTER2';
export const INCREMENT_COUNTER2 = 'INCREMENT_COUNTER2';
export const DECREMENT_COUNTER2 = 'DECREMENT_COUNTER2';